# Rotated vertical monitor (DP-2)
monitor=DP-2,1920x1080@144,2560x0,1,transform,1

# Main horizontal monitor (DP-3)
monitor=DP-3,2560x1440@180,0x600,1

# Pin workspaces 9 and 10 to the vertical monitor
workspace=9,monitor:DP-2
workspace=10,monitor:DP-2,default:true

