#!/bin/bash
# setup-monitors.sh
# Detects connected monitors and generates a baseline monitor.conf.
# Run this on a new machine after first boot into Hyprland, then
# edit the result if needed and run: hyprctl reload

CONF="$HOME/.config/hypr/monitor.conf"

if [[ -f "$CONF" ]]; then
    BAK="${CONF}.bak"
    cp "$CONF" "$BAK"
    echo "Backed up existing monitor.conf → $BAK"
fi

python3 - <<'EOF'
import json, subprocess, os

result = subprocess.run(["hyprctl", "monitors", "-j"], capture_output=True, text=True)
monitors = json.loads(result.stdout)

# Sort left to right by current x position
monitors.sort(key=lambda m: m.get("x", 0))

lines = [
    "# Auto-generated by setup-monitors.sh — edit as needed",
    "# Hyprland monitor format:",
    "#   monitor=NAME, WxH@Hz, XxY, scale [,transform, N]",
    "#   transform: 0=normal 1=90° 2=180° 3=270°",
    "",
]

x_offset = 0
vertical_monitor = None
for m in monitors:
    name      = m["name"]
    w         = m["width"]
    h         = m["height"]
    refresh   = round(m["refreshRate"])
    scale     = int(m.get("scale", 1))
    transform = m.get("transform", 0)

    line = f"monitor={name},{w}x{h}@{refresh},{x_offset}x0,{scale}"
    if transform:
        line += f",transform,{transform}"
        vertical_monitor = name
    lines.append(line)
    lines.append("")

    x_offset += w

if vertical_monitor:
    lines += [
        f"# Pin workspaces 9 and 10 to the vertical monitor ({vertical_monitor})",
        f"workspace=9,monitor:{vertical_monitor}",
        f"workspace=10,monitor:{vertical_monitor},default:true",
        "",
    ]

conf_path = os.path.expanduser("~/.config/hypr/monitor.conf")
content = "\n".join(lines)
with open(conf_path, "w") as f:
    f.write(content)

print(content)
print(f"Written to {conf_path}")
EOF

echo ""
echo "Next steps:"
echo "  1. Edit $CONF if you need to adjust positions, rotation, or scale"
echo "  2. Run: hyprctl reload"
echo "  3. Run: ~/.config/hypr/setup-wallpaper.sh"
