[window]
  [window.padding]
  x = 0
  y = 0

[font.normal]
family = "FiraMono Nerd Font"
style = "Regular"

[font.bold]
style = "Bold"

[font.italic]
style = "Italic"

[colors.primary]
background = "0x282828"
foreground = "0xdfbf8e"

[colors.normal]
black = "0x665c54"
red = "0xea6962"
green = "0xa9b665"
yellow = "0xe78a4e"
blue = "0x7daea3"
magenta = "0xd3869b"
cyan = "0x89b482"
white = "0xdfbf8e"

[colors.bright]
black = "0x928374"
red = "0xea6962"
green = "0xa9b665"
yellow = "0xe3a84e"
blue = "0x7daea3"
magenta = "0xd3869b"
cyan = "0x89b482"
white = "0xdfbf8e"


[[keyboard.bindings]]
key = "H"
mods = "Control|Shift"
chars = "\u001b[72;6u"

[[keyboard.bindings]]
key = "J"
mods = "Control|Shift"
chars = "\u001b[74;6u"

[[keyboard.bindings]]
key = "K"
mods = "Control|Shift"
chars = "\u001b[75;6u"

[[keyboard.bindings]]
key = "L"
mods = "Control|Shift"
chars = "\u001b[76;6u"

[[keyboard.bindings]]
key = "I"
mods = "Control"
chars = "\u001b[105;5u"

[[keyboard.bindings]]
key = "Period"
mods = "Control"
chars = "\u001b[46;5u"

[[keyboard.bindings]]
key = "Comma"
mods = "Control"
chars = "\u001b[44;5u"

[[keyboard.bindings]]
key = "Semicolon"
mods = "Control"
chars = "\u001b[59;5u"
